apiVersion: skaffold/v2beta26
kind: Config

build:
  artifacts:
    - image: docker.io/golang-enthusiast/cowboy-app
      docker:
        dockerfile: ./docker/app/Dockerfile
    - image: docker.io/golang-enthusiast/cowboy-app-cron
      docker:
        dockerfile: ./docker/cron/Dockerfile        
    - image: docker.io/golang-enthusiast/cowboy-app-data-migration
      context: ./migrations  
  local:
    push: false   
    concurrency: 1

deploy:
  helm:
    flags:
      upgrade: ["--timeout", "30m"]
      install: ["--timeout", "30m"]
    releases:
    - name: demo
      chartPath: helm/cowboy-app
      wait: true
      artifactOverrides:
        skaffoldImage: docker.io/golang-enthusiast/cowboy-app
        cron.skaffoldImage: docker.io/golang-enthusiast/cowboy-app-cron
        migration.skaffoldImage: docker.io/golang-enthusiast/cowboy-app-data-migration
      setValueTemplates:
        skaffold: true 
        image.pullPolicy: Never
        localstack.enabled: true
