apiVersion: v2
name: cowboy-app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: latest

dependencies:
  - name: localstack
    version: 0.3.7
    repository: https://localstack.github.io/helm-charts
    condition: localstack.enabled
    alias: localstack
