# Default values for cowboy-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  hostname: docker.io
  repository: /golang-enthusiast/cowboy-app
  tag: local
  pullPolicy: IfNotPresent  

cron:
  image:
    hostname: docker.io
    repository: /golang-enthusiast/cowboy-app-cron      

migration:
  image:
    hostname: docker.io
    repository: /golang-enthusiast/cowboy-app-data-migration
  config:
    directory: migrations
    table: migrations

service:
  type: ClusterIP
  protocol: TCP
  port: 6565

ingress:
  name: http
  protocol: HTTP
  port: 80
  extension: svc.cluster.local

serviceAccount:
  create: true  

skaffold: false

localstack:
  enabled: false
  protocol: "http://"
  host: localstack
  service:
    edgeService:
      targetPort: 4566
  extraEnvVars:
    - name: DEFAULT_REGION
      value: "us-east-1"
    - name: SERVICES
      value: "dynamodb,sqs"

aws:
  key:
    access: test
    secret: test
  region: us-east-1

cowboy:
  tableName: cowboys