apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cowboy-app.fullname" . }}-data-migration-job
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "cowboy-app.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cowboy-app.name" . }}-migration
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: init-data-migration
          image: busybox
          command: ['sh', '-c', "until nc -w 2 {{ .Release.Name }}-{{ index .Values.localstack.host }} {{ .Values.localstack.service.edgeService.targetPort }}; do echo Waiting for {{ .Release.Name }}-{{ index .Values.localstack.host }}; sleep 2; done;"]
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "cowboy-app.migration-image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_MOCK_SERVER_ADDRESS
              value: "{{ .Values.localstack.protocol }}{{ .Release.Name }}-{{ index .Values.localstack.host }}:{{ index .Values.localstack.service.edgeService.targetPort }}"  
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}    
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.key.access | quote }}     
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.key.secret | quote }}
            - name: MIGRATIONS_DIR
              value: {{ .Values.migration.config.directory | quote }} 
            - name: MIGRATIONS_TABLE_NAME
              value: {{ .Values.migration.config.table | quote }}
